#!/usr/bin/env python3
"""Generate build/<target>/ps/golden_hash.hpp -- the SHA-256 golden digest
(src/pl/sha256_hash, see HASH_KERNEL.md) of the SAME data
gen_golden_data.py's golden_data.hpp encodes for the CURRENT tile
geometry/REPEAT_N (src/include/aie_settings.hpp).

Invoked by the Makefile, never by hand -- see the rule building
$(GOLDEN_HASH_HDR) in Makefile.

Why this exists: a tile-geometry or REPEAT_N change produces a completely
different golden_data.hpp (different rowA/colA/colB -> different base file;
different REPEAT_N -> different replication count), and per HASH_KERNEL.md's
own avalanche-property measurement, even a single-element change anywhere in
that data flips ~half the digest's bits -- so the golden hash has to be
re-derived every time golden_data.hpp is, exactly the same "switch depending
on block size" problem gen_golden_data.py already solves for the raw data.

This script deliberately reuses gen_golden_data.py's own geometry-parsing,
base-file-resolution, and REPEAT_N-replication logic (imported, not
re-implemented) instead of duplicating it: the digest is only meaningful if
computed over EXACTLY the same bytes golden_data.hpp's `golden_data` array
holds, so importing that one shared implementation makes the two
structurally unable to disagree, rather than relying on two hand-written
copies staying in sync.
"""

import argparse
import hashlib
import os
import struct
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import gen_golden_data as ggd  # noqa: E402  (path insert must come first)


def pack_be(values):
    """Big-endian per-signed-int16-element packing -- the exact convention
    src/pl/sha256_hash/sha256_hash.cpp and experiments/hash_sha256_aie's
    reference_hash.py both use (see sha256_hash.hpp's header comment and
    pl_hash_control.cpp, which feeds the PL kernel the same int16_t C
    buffer this hashes here)."""
    return b"".join(struct.pack(">h", v) for v in values)


def render(base_path, settings_path, repeat_n, digest):
    hex_bytes = ", ".join(f"0x{b:02x}" for b in digest)
    return f"""// Auto-generated by scripts/gen_golden_hash.py from {base_path}
// (REPEAT_N=1 base data) and the REPEAT_N value in {settings_path} -- DO
// NOT EDIT. Mirrors build/<target>/ps/golden_data.hpp exactly (same base
// file, same REPEAT_N={repeat_n} replication, see gen_golden_data.py) --
// this is the SHA-256 digest (src/pl/sha256_hash, HASH_KERNEL.md) of that
// identical replicated block, packed with the same big-endian-per-int16-
// element convention pl_hash_control.cpp/sha256_hash.cpp use. To change the
// golden reference, edit/re-capture {base_path} (see gen_golden_data.py's
// `capture` subcommand); to pick up a new REPEAT_N, just rebuild.

#pragma once

#include "pl_hash_control.hpp"

namespace aie_benchmark::data {{
    inline constexpr unsigned char golden_hash[pl_hash_control::DIGEST_SIZE] = {{
        {hex_bytes}
    }};
}}
"""


def cmd_generate(args):
    rowA, colA, colB, repeat_n = ggd.parse_geometry(args.settings)
    base_path = args.base
    if base_path is None:
        base_path = os.path.join(args.base_dir, ggd.base_filename_for(rowA, colA, colB))
    if not os.path.exists(base_path):
        sys.exit(
            f"error: no captured golden data for rowA={rowA} colA={colA} colB={colB} -- "
            f"expected {base_path}. Capture it first, e.g.:\n"
            f"  python3 {os.path.join(os.path.dirname(__file__), 'gen_golden_data.py')} capture "
            f"--uart-log <uart_capture.log> --settings {args.settings} "
            f"--base-dir {os.path.dirname(base_path) or '.'}"
        )
    base_values = ggd.parse_base_data(base_path)
    measured = base_values * repeat_n
    digest = hashlib.sha256(pack_be(measured)).digest()
    content = render(base_path, args.settings, repeat_n, digest)
    with open(args.output, "w") as f:
        f.write(content)


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = ap.add_subparsers(dest="command", required=True)

    gen = sub.add_parser("generate", help="generate golden_hash.hpp from a base file (Makefile-invoked)")
    gen.add_argument("--base", help="explicit path to the REPEAT_N=1 base data file "
                                     "(default: auto-resolved from --base-dir + aie_settings.hpp's rowA/colA/colB, "
                                     "same resolution as gen_golden_data.py)")
    gen.add_argument("--base-dir", default="src/ps", help="directory to auto-resolve the base file in (default: src/ps)")
    gen.add_argument("--settings", required=True, help="path to aie_settings.hpp (read rowA/colA/colB/REPEAT_N from it)")
    gen.add_argument("--output", required=True, help="path to write the generated golden_hash.hpp")
    gen.set_defaults(func=cmd_generate)

    args = ap.parse_args()
    args.func(args)


if __name__ == "__main__":
    main()
