#!/usr/bin/env python3
"""Generate build/<target>/aie/static_ab_data.hpp -- the compile-time A/B
operand data baked directly into every gemm[i] kernel instance's own ELF
under aie_settings.hpp's USE_STATIC_AB (see
src/aie/kernels/gemm_blocked_kernel.cpp, N_KERNELS_34_STATIC_AB_EXPERIMENT.md).

Invoked by the Makefile, never by hand -- see the rule building
$(STATIC_AB_DATA_HDR) in Makefile. To (re)create the base files this reads,
use scripts/gen_gemm_matrices.py.

Why this exists: USE_STATIC_AB used to bake in an arbitrary, deterministic
but non-meaningful int8 pattern (ConstPattern in gemm_blocked_kernel.cpp) --
every tile computed identically to every other tile, which was enough for
this project's fault-injection goal, but wasn't real GeMM test data. This
script instead reads the SAME real int8 GeMM matrices
scripts/gen_gemm_matrices.py generates for the dynamic-A/B path
(gen_input_data.py's input_data.hpp), so both the static and dynamic A/B
paths draw from one shared, geometry-keyed source of truth (never two
hand-written copies that could drift apart) -- exactly gen_golden_data.py's
own reasoning for golden_data.hpp, applied here to the OTHER end of the
data path.

Unlike input_data.hpp (replicated settings::input_count times, one C++
array per BenchmarkInput slot), this header holds ONE untouched A_SIZE/
B_SIZE-element chunk each, typed as the kernel's own A_TYPE/B_TYPE (not
BenchmarkInput/int32) -- USE_STATIC_AB has no PS-side "how many different
inputs" concept at all: it's the SAME broadcast data compiled once into
every kernel instance's ELF, consumed directly without any replication or
narrowing step.
"""

import argparse
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import gen_golden_data as ggd  # noqa: E402  (path insert must come first)


def base_filename_for(rowA, colA, colB, dtype, operand):
    return f"input_data_base_rowA_{rowA}_colA_{colA}_colB_{colB}_{dtype}_{operand}.txt"


def resolve_base(explicit, base_dir, rowA, colA, colB, dtype, operand):
    if explicit is not None:
        return explicit
    return os.path.join(base_dir, base_filename_for(rowA, colA, colB, dtype, operand))


def require_base(base_path, rowA, colA, colB, operand, settings_path):
    if not os.path.exists(base_path):
        sys.exit(
            f"error: no generated input data for rowA={rowA} colA={colA} colB={colB} "
            f"operand {operand} -- expected {base_path}. Generate it first, e.g.:\n"
            f"  python3 {os.path.join(os.path.dirname(__file__), 'gen_gemm_matrices.py')} "
            f"--rowA {rowA} --colA {colA} --colB {colB} "
            f"--settings {settings_path} --base-dir {os.path.dirname(base_path) or '.'}"
        )


def render(base_a, base_b, a_values, b_values):
    return f"""// Auto-generated by scripts/gen_static_ab_data.py from {base_a} and {base_b}
// -- DO NOT EDIT. Compile-time A/B operand data for the GeMM AIE kernel's
// USE_STATIC_AB path (src/aie/kernels/gemm_blocked_kernel.cpp), baked into
// every kernel instance's own ELF instead of being DMA'd in from DDR (see
// aie_settings.hpp's USE_STATIC_AB comment). Real int8 GeMM matrix data
// (scripts/gen_gemm_matrices.py), not an arbitrary formula -- the SAME
// source scripts/gen_input_data.py draws from for the dynamic-A/B path's
// input_data.hpp, so the two can't drift apart. To change the operands,
// regenerate the base files; to pick up a new tile geometry, just rebuild
// (this file is a Make prerequisite of the AIE graph compile).

#pragma once

#include "aie_settings.hpp"

namespace static_ab_data {{
    inline constexpr A_TYPE A[{len(a_values)}] = {{
{ggd.format_array(a_values)}
    }};
    inline constexpr B_TYPE B[{len(b_values)}] = {{
{ggd.format_array(b_values)}
    }};

    static_assert(sizeof(A) / sizeof(A[0]) == (unsigned)A_SIZE,
        "static_ab_data.hpp: A size doesn't match aie_settings.hpp's A_SIZE -- "
        "regenerate (make clean/build), or if A_SIZE itself changed (rowA/colA/TILE_* "
        "edited in aie_settings.hpp), {base_a} needs regenerating for the new tile "
        "geometry (scripts/gen_gemm_matrices.py).");
    static_assert(sizeof(B) / sizeof(B[0]) == (unsigned)B_SIZE,
        "static_ab_data.hpp: B size doesn't match aie_settings.hpp's B_SIZE -- see A's "
        "static_assert above; {base_b} needs regenerating (scripts/gen_gemm_matrices.py) "
        "if B_SIZE itself changed.");
}}
"""


def cmd_generate(args):
    rowA, colA, colB, _repeat_n = ggd.parse_geometry(args.settings)
    dtype = ggd.parse_a_type(args.settings)

    base_a = resolve_base(args.base_a, args.base_dir, rowA, colA, colB, dtype, "A")
    base_b = resolve_base(args.base_b, args.base_dir, rowA, colA, colB, dtype, "B")
    require_base(base_a, rowA, colA, colB, "A", args.settings)
    require_base(base_b, rowA, colA, colB, "B", args.settings)

    a_values = ggd.parse_base_data(base_a)
    b_values = ggd.parse_base_data(base_b)

    content = render(base_a, base_b, a_values, b_values)
    with open(args.output, "w") as f:
        f.write(content)


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = ap.add_subparsers(dest="command", required=True)

    gen = sub.add_parser("generate", help="generate static_ab_data.hpp from base files (Makefile-invoked)")
    gen.add_argument("--base-a", help="explicit path to the A-operand base data file "
                                       "(default: auto-resolved from --base-dir + aie_settings.hpp's rowA/colA/colB)")
    gen.add_argument("--base-b", help="explicit path to the B-operand base data file (same default rule as --base-a)")
    gen.add_argument("--base-dir", default="src/ps", help="directory to auto-resolve the base files in (default: src/ps)")
    gen.add_argument("--settings", required=True, help="path to aie_settings.hpp (read rowA/colA/colB from it)")
    gen.add_argument("--output", required=True, help="path to write the generated static_ab_data.hpp")
    gen.set_defaults(func=cmd_generate)

    args = ap.parse_args()
    args.func(args)


if __name__ == "__main__":
    main()
