#!/usr/bin/env python3
"""Generate build/<target>/pl/sha256_hash_num_elements.hpp -- the element
count src/pl/sha256_hash/sha256_hash.hpp's HLS kernel synthesizes for.

Invoked by the Makefile, never by hand -- see the rule building
$(SHA256_NUM_ELEMENTS_HDR) in Makefile.

Why this exists: sha256_hash.hpp's NUM_ELEMENTS must equal
src/include/aie_settings.hpp's C_TOTAL_SIZE (C_BLOCK_SIZE * rowA * colB *
REPEAT_N, where C_BLOCK_SIZE = TILE_M * TILE_N) -- the exact element count
the PS hands the kernel per hash. sha256_hash.hpp can't #include
aie_settings.hpp itself (that header pulls in <adf.h>/aie_api/aie.hpp,
invalid for HLS v++ --mode hls synthesis), so this script parses the same
constants out of aie_settings.hpp's text (same approach gen_golden_data.py
already uses for rowA/colA/colB/REPEAT_N) and computes C_TOTAL_SIZE
independently, generating a tiny header the HLS kernel compile can include
instead. This removes the previous hand-maintained hard-coded copy (and the
silent-drift risk that came with it) for every rowA/colA/colB/REPEAT_N
sweep.
"""

import argparse
import re
import sys

TILE_M_RE   = re.compile(r"constexpr\s+int\s+TILE_M\s*=\s*(\d+)\s*;")
TILE_N_RE   = re.compile(r"constexpr\s+int\s+TILE_N\s*=\s*(\d+)\s*;")
ROWA_RE     = re.compile(r"constexpr\s+unsigned\s+rowA\s*=\s*(\d+)\s*;")
COLB_RE     = re.compile(r"constexpr\s+unsigned\s+colB\s*=\s*(\d+)\s*;")
REPEAT_N_RE = re.compile(r"constexpr\s+unsigned\s+REPEAT_N\s*=\s*(\d+)\s*;")


def parse_int_define(text, pattern, name, path):
    m = pattern.search(text)
    if not m:
        sys.exit(f"error: could not find '{name}' in {path}")
    return int(m.group(1))


def render(settings_path, num_elements):
    return f"""// Auto-generated by scripts/gen_sha256_num_elements.py from
// {settings_path} -- DO NOT EDIT. Mirrors aie_settings.hpp's C_TOTAL_SIZE
// (C_BLOCK_SIZE * rowA * colB * REPEAT_N, C_BLOCK_SIZE = TILE_M * TILE_N)
// for the CURRENT tile geometry -- see sha256_hash.hpp's header comment for
// why this can't just #include aie_settings.hpp directly. Changing
// rowA/colA/colB/REPEAT_N and rebuilding regenerates this automatically;
// nothing here needs hand-editing.

#pragma once

constexpr int SHA256_HASH_NUM_ELEMENTS = {num_elements};
"""


def cmd_generate(args):
    text = open(args.settings).read()
    tile_m = parse_int_define(text, TILE_M_RE, "TILE_M", args.settings)
    tile_n = parse_int_define(text, TILE_N_RE, "TILE_N", args.settings)
    rowA = parse_int_define(text, ROWA_RE, "rowA", args.settings)
    colB = parse_int_define(text, COLB_RE, "colB", args.settings)
    repeat_n = parse_int_define(text, REPEAT_N_RE, "REPEAT_N", args.settings)

    num_elements = tile_m * tile_n * rowA * colB * repeat_n
    with open(args.output, "w") as f:
        f.write(render(args.settings, num_elements))


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--settings", required=True, help="path to aie_settings.hpp (read TILE_M/TILE_N/rowA/colB/REPEAT_N from it)")
    ap.add_argument("--output", required=True, help="path to write the generated sha256_hash_num_elements.hpp")
    ap.set_defaults(func=cmd_generate)

    args = ap.parse_args()
    args.func(args)


if __name__ == "__main__":
    main()
